== Soins de santé
Un organisme de sécurité sociale souhaite développer une application gérant des patients, leur médecin traitant et des médecins spécialistes. Une personne est soit un assuré, soit un médecin, un médecin pouvant être malade et être assuré. Un médecin est soit généraliste, soit spécialiste, un généraliste ne pouvant pas être spécialiste et inversement. Un patient a choisi ou non son médecin traitant. Un patient consulte, à une date donnée, un généraliste. Lors des consultations, le généraliste peut ou non prescrire une ou plusieurs consultations chez un spécialiste. Cette application peut être utilisée par l’organisme de sécurité sociale pour inscrire un assuré, enregistrer un médecin traitant pour un assuré, enregistrer des feuilles de maladie et effectuer des remboursements. Tout médecin peut également, via l’application, enregistrer une feuille de maladie, prescrire des médicaments et prescrire une consultation chez un spécialiste. Question : modélisez un tel système : analysez et concevez,
